### ISSUE TITLE
error with opam-builder 2.0

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/opam-builder#37]
```
cmd=OPAM_BUILD=/home/lefessan/BUILDER/4.05.0+beta3/builder.cache opam.dev install --root /home/lefessan/BUILDER/4.05.0+beta3/.opam --switch 4.05.0+beta3 --yes --quiet base-unix.base > check-install.log 2>&1
Fatal error: exception Sys_error("check-install.log: No such file or directory")
Raised by primitive operation at file "pervasives.ml", line 366, characters 28-54
Called from file "pervasives.ml" (inlined), line 374, characters 2-47
Called from file "./libs/ocplib-file/fileString.ml", line 154, characters 11-31
Called from file "./tools/opam-builder/checkBuild.ml", line 91, characters 20-49
Called from file "./tools/opam-builder/checkBuild.ml", line 164, characters 9-63
Called from file "./tools/opam-builder/checkUpdate.ml", line 64, characters 6-10
Called from file "./tools/opam-builder/checkBuild.ml", line 214, characters 2-354
Called from file "./tools/opam-builder/checkBuild.ml", line 308, characters 8-83
Called from file "list.ml", line 77, characters 12-15
Called from file "./tools/opam-builder/commandBuild.ml", line 47, characters 6-43
Called from file "./tools/opam-builder/commandWatch.ml", line 72, characters 18-48
Called from file "./tools/opam-builder/commandWatch.ml", line 51, characters 10-18
Called from file "./tools/opam-builder/builder.ml", line 237, characters 2-60
```

**Comment by lefessan** [comment]
And another one in 4.02.1:

Package charrua-core. Selected version 0.1 is not the most recent (charrua-core.0.3)
Package charrua-core. Selected version 0.1 is not the most recent (charrua-core.0.4)
Package charrua-core. Selected version 0.1 is not the most recent (charrua-core.0.5)
Package charrua-core. Selected version 0.1 is not the most recent (charrua-core.0.6)
Package charrua-core. Selected version 0.1 is not the most recent (charrua-core.0.7)
Version charrua-unix.0.2 could not be found !!!
Fatal error: exception File "./tools/opam-builder/checkStats.ml", line 44, characters 25-31: Assertion failed
Raised at file "./tools/opam-builder/checkStats.ml", line 44, characters 25-37
Called from file "./tools/opam-builder/checkStats.ml", line 70, characters 26-60
Called from file "list.ml", line 77, characters 12-15
Called from file "./tools/opam-builder/checkStats.ml", line 69, characters 14-735
Called from file "map.ml", line 172, characters 20-25
Called from file "map.ml", line 172, characters 10-18
Called from file "map.ml", line 172, characters 10-18
Called from file "map.ml", line 172, characters 10-18
Called from file "map.ml", line 172, characters 10-18
Called from file "map.ml", line 172, characters 10-18
Called from file "./tools/opam-builder/checkStats.ml", line 61, characters 2-1023
Called from file "./tools/opam-builder/commandWeather.ml", line 118, characters 14-43
Called from file "./tools/opam-builder/commandBuild.ml", line 44, characters 25-52
Called from file "./tools/opam-builder/commandSwitch.ml", line 40, characters 16-46
Called from file "./tools/opam-builder/commandWatch.ml", line 55, characters 10-18
Called from file "./tools/opam-builder/builder.ml", line 257, characters 2-60

**Comment by lefessan** [comment]
And in the interface:
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://builder/json/opam-builder.html?' cannot be created in a document with origin 'http://fabrice.lefessant.net' and URL 'http://fabrice.lefessant.net//builder/json/opam-builder.html'.
    at history_init (http://fabrice.lefessant.net//builder/json/opam-builder.js:234:13)
    at body_onload (http://fabrice.lefessant.net//builder/json/opam-builder.js:266:5)
    at onload (http://fabrice.lefessant.net//builder/json/opam-builder.html:7:51)
history_init @ opam-builder.js:234
body_onload @ opam-builder.js:266
onload @ opam-builder.html:7
